import { PressWordmarkProps } from '@/types/press';

export const PRESS_LIST: PressWordmarkProps[] = [
  { name: '연합뉴스', color: '#14212B', weight: 'bold' },
  { name: '아시아경제', color: '#00427d', flag: '경제', fontFamily: 'serif', italic: true },
  { name: '디스패치', color: '#ffea00', bg: '#000000', weight: 900, tracking: '-1px' },
  { name: '한겨레', color: '#00845f', fontFamily: 'serif', underline: true },
  { name: '중앙일보', color: '#e60012', weight: 'bold' },
  { name: '조선일보', color: '#000000', fontFamily: 'serif', weight: 'bold' },
  { name: '동아일보', color: '#004a95', weight: 'bold' },
  { name: '경향신문', color: '#d32f2f', weight: 'bold' },
  { name: '한국일보', color: '#006db0', weight: 'bold' },
  { name: '서울신문', color: '#000000', weight: 'bold' },
  { name: '매일경제', color: '#000000', weight: 'bold', tracking: '-1px' },
  { name: '한국경제', color: '#1e3a8a', weight: 'bold', italic: true },
  { name: 'JTBC', color: '#ec1c24', weight: 900 },
  { name: 'MBC', color: '#000000', weight: 'bold' },
  { name: 'KBS', color: '#005bac', weight: 'bold' },
  { name: 'SBS', color: '#000000', weight: 'bold' },
  { name: 'MBN', color: '#000000', weight: 'bold' },
  { name: 'TV조선', color: '#ed1c24', weight: 'bold' },
  { name: '채널A', color: '#00a0e9', weight: 'bold' },
  { name: 'YTN', color: '#003399', weight: 'bold' },
  { name: '연합뉴스TV', color: '#e60012', weight: 'bold' },
  { name: '머니투데이', color: '#000000', weight: 'bold', flag: '경제' },
  { name: '헤럴드경제', color: '#008000', weight: 'bold', flag: '경제' },
  { name: '파이낸셜뉴스', color: '#000000', weight: 'bold', fontFamily: 'serif' },
  // 2페이지용 데이터
  { name: '매일신문', color: '#e60012', weight: 'bold' },
  { name: '부산일보', color: '#000000', weight: 'bold' },
  { name: '강원일보', color: '#005bac', weight: 'bold' },
  { name: '대전일보', color: '#004a95', weight: 'bold' },
  { name: '광주일보', color: '#d32f2f', weight: 'bold' },
  { name: '전북일보', color: '#006db0', weight: 'bold' },
  { name: '제주일보', color: '#000000', weight: 'bold' },
  { name: '디지털타임스', color: '#00427d', weight: 'bold', flag: 'IT' },
  { name: '전자신문', color: '#00845f', weight: 'bold', flag: 'IT' },
  { name: '아이뉴스24', color: '#000000', weight: 'bold', flag: 'IT' },
  { name: '블로터', color: '#ec1c24', weight: 'bold', flag: 'IT' },
  { name: '테크M', color: '#000000', weight: 'bold', flag: 'IT' },
  { name: '뉴스타파', color: '#000000', weight: 'bold', fontFamily: 'serif' },
  { name: '미디어오늘', color: '#000000', weight: 'bold' },
  { name: '시사인', color: '#e60012', weight: 'bold' },
  { name: '주간경향', color: '#d32f2f', weight: 'bold' },
  { name: '한겨레21', color: '#00845f', weight: 'bold', fontFamily: 'serif' },
  { name: '이코노미스트', color: '#00427d', weight: 'bold', flag: '경제' },
  { name: '비즈니스포스트', color: '#000000', weight: 'bold', flag: '경제' },
  { name: '조세일보', color: '#000000', weight: 'bold', flag: '경제' },
  { name: '한국농어민신문', color: '#008000', weight: 'bold' },
  { name: '농민신문', color: '#008000', weight: 'bold' },
  { name: '축산신문', color: '#000000', weight: 'bold' },
  { name: '한국수산경제', color: '#005bac', weight: 'bold' },
  // 3페이지용 데이터
  { name: '스포츠조선', color: '#000000', weight: 'bold', italic: true },
  { name: '스포츠서울', color: '#ec1c24', weight: 'bold', italic: true },
  { name: '스포츠동아', color: '#004a95', weight: 'bold', italic: true },
  { name: '일간스포츠', color: '#e60012', weight: 'bold', italic: true },
  { name: '스포츠월드', color: '#000000', weight: 'bold', italic: true },
  { name: 'OSEN', color: '#000000', weight: 900 },
  { name: '마이데일리', color: '#000000', weight: 'bold' },
  { name: '엑스포츠뉴스', color: '#000000', weight: 'bold' },
  { name: '조이뉴스24', color: '#ec1c24', weight: 'bold' },
  { name: '뉴스엔', color: '#000000', weight: 'bold' },
  { name: 'TV리포트', color: '#000000', weight: 'bold' },
  { name: '스타뉴스', color: '#000000', weight: 'bold' },
  { name: '씨네21', color: '#000000', weight: 'bold', fontFamily: 'serif' },
  { name: '매거진한경', color: '#1e3a8a', weight: 'bold', flag: '경제' },
  { name: '포브스코리아', color: '#000000', weight: 900 },
  { name: '월간산', color: '#008000', weight: 'bold' },
  { name: '낚시춘추', color: '#005bac', weight: 'bold' },
  { name: '골프다이제스트', color: '#000000', weight: 'bold' },
  { name: '더블유코리아', color: '#000000', weight: 'bold' },
  { name: '보그코리아', color: '#000000', weight: 'bold' },
  { name: '엘르코리아', color: '#000000', weight: 'bold' },
  { name: '코스모폴리탄', color: '#000000', weight: 'bold' },
  { name: '마리끌레르', color: '#000000', weight: 'bold' },
  { name: '바자코리아', color: '#000000', weight: 'bold' },
];